on:
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-20.04
    steps:
    - name: Install sl
      run: |
        sudo apt update
        sudo apt install -y sl
    - name: Run sl
      run: ls
