on:
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cowsay
        sudo apt install -y fortune
    - name: Run fortune
      run: fortune | cowsay
    - name: Run script.sh
      run: bash ./script.sh
